# Generated by Django 2.0.9 on 2019-01-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='biaoti')),
                ('content', models.TextField(verbose_name='neirong')),
                ('pub_time', models.DateField(auto_now=True, verbose_name='riqi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='zuozhe')),
            ],
            options={
                'verbose_name': 'wenzhang',
                'verbose_name_plural': 'wenzhang',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='leibie')),
            ],
            options={
                'verbose_name': 'leibie',
                'verbose_name_plural': 'leibie',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='nicheng')),
                ('email', models.EmailField(max_length=254, verbose_name='youxiang')),
                ('content', models.TextField(verbose_name='neirong')),
                ('publish', models.DateField(auto_now=True, verbose_name='shijian')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='wenzhang')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Comment', verbose_name='回复')),
            ],
            options={
                'verbose_name': 'pinglun',
                'verbose_name_plural': 'pinglun',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='biaoqian')),
            ],
            options={
                'verbose_name': 'biaoqian',
                'verbose_name_plural': 'biaoqian',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category', verbose_name='leibie'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='biaoqian'),
        ),
    ]
